package com.blog_application.blog_application.model;

public enum Tag {
    TECH_INNOVATION, CODING_LIFE, DIGITAL_TRANSFORMATION, GADGETS, SOFTWARE_ENGINEERING,
    HEALTHY_LIVING, MENTAL_WELLNESS, FITNESS_JOURNEY, NUTRITION_TIPS, MINDFULNESS,
    TRAVEL_ADVENTURES, EXPLORE_THE_WORLD, TRAVEL_TIPS, WANDERLUST, CULTURAL_EXPERIENCES,
    SELF_IMPROVEMENT, PRODUCTIVITY_HACKS, MOTIVATIONAL_QUOTES, GOAL_SETTING,
    SUCCESS_MINDSET, FINANCIAL_FREEDOM, INVESTING_STRATEGIES, BUDGETING_TIPS,
    ENTREPRENEURSHIP, CRYPTO_INSIGHTS
}
